apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeviewer-pod-reader
  namespace: default
subjects:
  - kind: User
    name: kubeviewer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io