apiVersion: v1
kind: Service
metadata:
  name: multitool-service
spec:
  selector:
    app: multitool-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: multitool
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP