apiVersion: v1
kind: Service
metadata:
  name: svc-multi-container-nodeport
  namespace: mynamespace
spec:
  ports:
    - name: nginx
      port: 9001
      targetPort: 80
      nodePort: 30001
    - name: multitool
      port: 9002
      targetPort: 8080
      nodePort: 30002
  selector:
    app: app-multi-container
  type: NodePort