apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 443 ssl;
        server_name localhost;
        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;
        root /usr/share/nginx/html;
        index index.html;

        location / {
          try_files $uri $uri/ =404;
        }
      }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>My own Nginx Page</title>
    </head>
    <body>
        <h1>Netology DevOps with HTTPS!</h1>
    </body>
    </html>